### ISSUE TITLE
html report not generating

### ISSUE THREAD

**Issue by Isuresh** [wolf99/test-ceedling-gcov#1]
Hi @wolf99 

below is my project file

:gcov:
:html_report_type: detailed

:gcov_linker:
:executable: gcc-5
:arguments:
- -ftest-coverage
- -fprofile-arcs
- -O0 # never optimize for this
- ${1}
- -lm
- -D$: COLLECTION_DEFINES_TEST_AND_VENDOR
- -I"$": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR
- -I"$": COLLECTION_PATHS_TEST_TOOLCHAIN_INCLUDE
- -o ${2}
:gcov_fixture:
:executable: ${1}
:gcov_report:
:executable: gcov
:arguments:
- -n
- -p
- -b
- -o "$": GCOV_BUILD_OUTPUT_PATH
- ""${1}""
:gcov_post_report:
:executable: gcovr
:optional: FALSE
:arguments:
- -p
- -b
- -e '.tools.|.build.|.vendor/ceedling.|.test/test.'
- --object-directory= "$": GCOV_BUILD_OUTPUT_PATH
- --html
- --html-details
- -o build/artifacts/gcov/index.html

with above configuration i am able build test cases with out any error by using ceedling gcov:all but it is not generating html coverage report can you please help me .

**Comment by wolf99** [comment]
Hi, @Isuresh can you let me know what version of gcovr you have installed? (gcovr has a `--version` option to find this).

**Comment by Isuresh** [comment]
Hi @wolf99 thanks for update  
i am getting below error when i am trying to run gcovr in windows command line , i did not install gcovr separately it is already installed along with python, available in this path   C:\python36\Scripts\gcovr.

'gcovr' is not recognized as an internal or external command, operable program or batch file.

thanks 
suresh

**Comment by wolf99** [comment]
In this case you will likely need to use the command as follows `python gcovr --version`

**Comment by Isuresh** [comment]
i have tried that command it is giving below error 
python: can't open file 'gcovr': [Errno 2] No such file or directory

python details what i have

Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)] on win32

**Comment by wolf99** [comment]
And what's the output you got from `ceedling utils:gocv`?

**Comment by Isuresh** [comment]
Hi @wolf99  below response i am getting for that command  

Creating a detailed html report of gcov results in build/artifacts/gcov/GcovCoverageResults.html...
rake aborted!
Errno::ENOENT: No such file or directory - gcovr -p -b -e "'^vendor.*|^build.*|^test.*|^lib.*'" --html --html-details -r . -o  "build/artifacts/gcov/Gco
vCoverageResults.html"
C:/Users/sit8cob/Desktop/UnitTest6.02.02/UnitTestCgms/vendor/ceedling/lib/ceedling/system_wrapper.rb:45:in ``'
C:/Users/sit8cob/Desktop/UnitTest6.02.02/UnitTestCgms/vendor/ceedling/lib/ceedling/system_wrapper.rb:45:in `shell_backticks'
C:/Users/sit8cob/Desktop/UnitTest6.02.02/UnitTestCgms/vendor/ceedling/lib/ceedling/tool_executor.rb:68:in `exec'
vendor/ceedling/plugins/gcov/gcov.rake:168:in `block (2 levels) in <top (required)>'
C:/Ruby23/bin/ceedling:23:in `load'
C:/Ruby23/bin/ceedling:23:in `<main>'
Tasks: TOP => utils:gcov
(See full trace by running task with --trace)
ERROR: Ceedling Failed

**Comment by wolf99** [comment]
I'm not fully sure if this is a ceedling error or a gcovr error as gcovr has seen a lot of development around similar issues recently (which is why I asked for the gcovr version). But, if you are not even able to get gcovr to tell you it's version then you may need to uninstall and re-install gcovr.

See if you can install it and get it to run with a simple hello-world type program.

Other than this I'll have to direct you back to the ceedling or gcovr repositories as they would likely have better knowledge than I.
