### ISSUE TITLE
Failed Parsing Declaration Prototype!   declaration:

### ISSUE THREAD

**Issue by Isuresh** [wolf99/test-ceedling-gcov#2]
Hello , 
I am facing below issue while running unit test , can any one  please help to resolve this issue . 
_Bool Defined in <stdbool.h > as below 
#ifndef __cplusplus
#if defined(__CROSSWORKS_ARM) || defined(__SES_ARM) || defined(__SES_RISCV)
#define bool _Bool
#else
#define bool int
#endif
#define true 1
#define false 0
#endif
#define __bool_true_false_are_defined 1

#endif
In My project i am using __CROSSWORKS_ARM 
Failed Parsing Declaration Prototype!
  declaration: '_Bool hal_gpio_charging_get(void)'
  modifier: '_Bool'
  return: {:type => '', :name => 'cmock_to_return', :ptr? => false, :const? => false, :str => ' cmock_to_return', :void? => false}
  function: 'hal_gpio_charging_get'

Thanks
Suresh

**Comment by wolf99** [comment]
Hi Suresh

This is not the ceedling repository. It is on old test I ran that used ceedling.

You probably want to raise your issue on the ceedling repo instead. That is at: https://github.com/ThrowTheSwitch/Ceedling
